# Generated by Django 3.0.3 on 2020-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0002_auto_20200207_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
